export const reportSources = [
  {
    id: "gmi-nail-salon-2025",
    label: "GMI Insights",
    title: "Nail Salon Market Size, Share & Growth Forecasts",
    url: "https://www.gminsights.com/industry-analysis/nail-salon-market",
    accessed: "06/2026",
  },
  {
    id: "blvd-salon-stats-2025",
    label: "Boulevard",
    title: "Salon Trends & Industry Statistics",
    url: "https://www.joinblvd.com/blog/salon-trends-industry-statistics",
    accessed: "06/2026",
  },
  {
    id: "bls-cosmetologists",
    label: "BLS",
    title: "Barbers, Hairstylists, and Cosmetologists — Occupational Outlook",
    url: "https://www.bls.gov/ooh/personal-care-and-service/barbers-hairstylists-and-cosmetologists.htm",
    accessed: "06/2026",
  },
  {
    id: "bls-manicurists",
    label: "BLS",
    title: "Manicurists and Pedicurists — Occupational Outlook",
    url: "https://www.bls.gov/ooh/personal-care-and-service/manicurists-and-pedicurists.htm",
    accessed: "06/2026",
  },
  {
    id: "brightlocal-reviews-2024",
    label: "BrightLocal",
    title: "Local Consumer Review Survey 2024",
    url: "https://www.brightlocal.com/research/local-consumer-review-survey-2024/",
    accessed: "06/2026",
  },
  {
    id: "salon-today-retention",
    label: "Salon Today",
    title: "Boulevard Report — First-time visitor retention",
    url: "https://www.salontoday.com/1088748/boulevard-report-reveals-top-performing-salons-retain-56-more-first-time-visitor",
    accessed: "06/2026",
  },
  {
    id: "statista-nail-salons-us",
    label: "Statista / IBISWorld",
    title: "Nail Salons in the US — Industry Report",
    url: null,
    accessed: "06/2026",
    note: "study_id55027_nail-salons-in-the-us.pdf — Google Drive nghiên cứu nội bộ",
  },
  {
    id: "statista-consumer-csv-2023",
    label: "Statista Consumer Insights",
    title: "US Nail Product Users — Demographics & Purchase Criteria (n=1.092)",
    url: null,
    accessed: "07/2023",
    note: "export_20260626.csv — khảo sát người dùng sản phẩm nail tại Mỹ",
  },
  {
    id: "ucla-nail-files-2024",
    label: "UCLA Labor Center",
    title: "Nail Files — The Workforce Behind California's Nail Salon Industry",
    url: "https://laborcenter.berkeley.edu/nail-files/",
    accessed: "06/2026",
    note: "Nail_Files.pdf & Nail-Files-California-3.18.2024.pdf",
  },
  {
    id: "barnes-beauty-salons",
    label: "Barnes Reports",
    title: "Beauty Salons Industry Report (NAICS 812112)",
    url: null,
    accessed: "06/2026",
    note: "Beauty_Salons_Industry.pdf — Google Drive nghiên cứu nội bộ",
  },
  {
    id: "wve-exposed-report",
    label: "Women's Voices for the Earth",
    title: "Exposed — Chemical Hazards in Salon Products",
    url: null,
    accessed: "06/2026",
    note: "WVE Exposed report — Google Drive nghiên cứu nội bộ",
  },
  {
    id: "ca-bbc-art12",
    label: "CA Board of Barbering and Cosmetology",
    title: "Article 12 — Health and Safety (Disinfection & Ventilation)",
    url: "https://www.barbercosmo.ca.gov/laws_regs/act_rules.shtml",
    accessed: "06/2026",
  },
  {
    id: "nails-magazine-industry",
    label: "NAILS Magazine",
    title: "Industry Statistics & Trends",
    url: "https://www.nailsmag.com/",
    accessed: "06/2026",
  },
  {
    id: "pba-industry",
    label: "Professional Beauty Association",
    title: "Industry Resources & Economic Impact",
    url: "https://www.probeauty.org/",
    accessed: "06/2026",
  },
  {
    id: "regal-nails",
    label: "Regal Nails",
    title: "Salon-in-Retail Franchise Model",
    url: "https://www.regalnails.com/",
    accessed: "06/2026",
  },
  {
    id: "pro-nails-franchise",
    label: "Pro Nails",
    title: "National Nail Salon Franchise",
    url: "https://www.pronails.com/",
    accessed: "06/2026",
  },
  {
    id: "happy-nails-spa",
    label: "Happy Nails & Spa",
    title: "Regional Multi-Location Nail Chain (West Coast)",
    url: "https://www.happynails.com/",
    accessed: "06/2026",
  },
  {
    id: "nails-of-america",
    label: "Nails of America",
    title: "Franchise Nail Salon Brand",
    url: "https://www.nailsofamerica.com/",
    accessed: "06/2026",
  },
  {
    id: "wato-research",
    label: "Wato.one Research",
    title: "US Nail Salon Market Synthesis — WAT Pipeline",
    url: "https://github.com/wato-one/nailsalon_us_market",
    accessed: "06/2026",
    note: "Tổng hợp từ Drive + Firecrawl + Statista",
  },
  {
    id: "census-sd-county-2024",
    label: "Census Reporter",
    title: "San Diego County, CA — ACS 2024 Profile",
    url: "http://censusreporter.org/profiles/05000US06073-san-diego-county-ca/",
    accessed: "06/2026",
  },
  {
    id: "census-sd-city-2024",
    label: "Census Reporter",
    title: "San Diego city, CA — ACS 2024 Profile",
    url: "http://censusreporter.org/profiles/16000US0666000-san-diego-ca/",
    accessed: "06/2026",
  },
  {
    id: "census-santee-2024",
    label: "Census Reporter",
    title: "Santee, CA — ACS 2024 5-year Profile",
    url: "http://censusreporter.org/profiles/16000US0670224-santee-ca/",
    accessed: "06/2026",
  },
  {
    id: "santee-city-demographics",
    label: "City of Santee",
    title: "Population & Demographics — Santee, California",
    url: "https://www.cityofsanteeca.gov/business/economic-development/population--demographics",
    accessed: "06/2026",
  },
  {
    id: "cpi-east-county-income",
    label: "CPI San Diego",
    title: "Poverty, Income and Earnings in East County, 2018",
    url: "https://cpisandiego.org/poverty-income-earnings-east-county-2018/",
    accessed: "06/2026",
  },
  {
    id: "google-lk-santee",
    label: "Google",
    title: "LK Nail Salon — Google Maps / Business Profile",
    url: "https://www.google.com/maps/place/LK+Nail+Salon",
    accessed: "06/2026",
    note: "5,0★ · 276 đánh giá — Santee, CA",
  },
  {
    id: "yelp-lk-santee",
    label: "Yelp",
    title: "LK Nail Salon — Santee, CA (80 reviews)",
    url: "https://www.yelp.com/biz/lk-nail-salon-santee",
    accessed: "06/2026",
  },
  {
    id: "lk-company-site",
    label: "LK Nail Salon",
    title: "Website & dịch vụ — lknailsalonsantee.com",
    url: "https://lknailsalonsantee.com",
    accessed: "06/2026",
  },
  {
    id: "yelp-sunny-santee",
    label: "Yelp",
    title: "Sunny Nails & Spa — Santee (523 reviews)",
    url: "https://www.yelp.com/biz/sunny-nails-and-spa-santee-2",
    accessed: "06/2026",
  },
  {
    id: "yelp-polish-santee",
    label: "Yelp",
    title: "Polish Nails Spa — Santee (660 reviews)",
    url: "https://www.yelp.com/biz/polish-nails-spa-santee-3",
    accessed: "06/2026",
  },
  {
    id: "sunny-nails-santee",
    label: "Sunny Nails & Spa",
    title: "Nail Salon in Santee, CA 92071",
    url: "https://sunnynailsspasantee.com/",
    accessed: "06/2026",
  },
  {
    id: "polish-nails-santee",
    label: "Polish Nails Spa",
    title: "Polish Nails Spa LLC — Santee",
    url: "https://www.polishnailsspallcsantee.com/",
    accessed: "06/2026",
  },
  {
    id: "lavie-nails-santee",
    label: "La Vie Nails",
    title: "La Vie Nails & Spa — Santee",
    url: "https://www.yelp.com/biz/la-vie-nails-and-spa-santee",
    accessed: "06/2026",
  },
];
